# Change baseurl before deploy
baseurl      = "https://blog.jqcyx.qzz.io/"
languageCode = "zh-cn"
title        = "Jqcyx's Blog"

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
    pagerSize = 5
