# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "ğŸ’¤"
    subtitle = "å·²å®Œæˆä»Šæ—¥æˆ‘å¯¹ç€é“è´¨çš„æœºç®±è¸¢äº†äº”ä¸‹ç„¶åæŠŠé‚£å †ä»£ç åœ¨å†…å­˜ä¸­åˆ äº†ä¸€ä¸‹ç„¶åæŠŠæ¤…å­ç ¸åœ¨äº†åœ°æ¿ä¸Šå¤§å­¦ä¹ "
    avatar   = "img/avatar.png"

[article]
    headingAnchor = false
    math          = true
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = true
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.

[assets]
  [assets.katex]
    css = "https://cdn.bootcdn.net/ajax/libs/KaTeX/0.16.9/katex.min.css"
    js = "https://cdn.bootcdn.net/ajax/libs/KaTeX/0.16.9/katex.min.js"
    autoRender = "https://cdn.bootcdn.net/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js"